// MIT License
//
// Copyright (c) 2025 Takatoshi Kondo
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This module contains the internal MQTT implementation.
// The public mqtt module is dynamically generated by the make_alias macros.

// Include all the existing modules from the current directory structure
pub mod packet;
pub mod prelude;

pub mod connection;
pub use connection::role;
pub use connection::Connection;
pub use connection::GenericConnection;
pub use connection::SendBehavior;
pub use connection::Version;

pub mod common;
pub use common::{IntoPayload, ValueAllocator};

pub mod result_code;

pub mod make_alias;
pub use make_alias::{make_size_aliases, make_type_size_aliases};

// Re-export everything as mqtt_internal for external access
pub mod mqtt_internal {
    pub use super::*;
}
